package {[#PackageDao#]};

import java.util.List;
import commonTool.base.Page;
import {[#PackageVO#]}.{[#className#]};
import {[#PackageDto#]}.{[#className#]}Query;

public interface {[#className#]}Dao {
   
    /**
     * select some record by PK
     */
    public {[#className#]} selectByPK(Long pk);
    
    /**
     * select records by queryVO
     */
    public List selectByVO({[#className#]}Query queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage({[#className#]}Query queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * select records withoutBlobs by queryVO
     */
    public List selectByVOWithoutBLOBs({[#className#]}Query queryVO);
    
    /**
     * select page without blobs by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOWithoutBLOBsPage({[#className#]}Query queryVO,int pageIndex,int pageSize);

    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert({[#className#]} record);

    /**
     * update a record By PK
     */
    public int updateByPK({[#className#]} record);

	/**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public {[#className#]} save({[#className#]} record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}