package platform.shop.dao.impl;

import org.apache.log4j.Logger;

import platform.bean.BeanFactory;
import platform.shop.dao.ShopextDao;
import platform.shop.vo.Shopext;

import commonTool.base.BaseDao;
import commonTool.base.Page;
import commonTool.constant.CommonConstant;


public class ShopextDaoImpl extends BaseDao implements ShopextDao {

	static Logger log = Logger.getLogger(ShopextDaoImpl.class.getName());
	
    /**
     *
     */
    public ShopextDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Shopext selectByPK(Long shopid){
    	if(shopid==null)
    		return null;
    	Shopext record = (Shopext) this.queryForObject("Shopext.selectByPK", shopid);
		return record;
    }
    
    public Page selectByVOPage(Shopext queryVO, int pageIndex, int pageSize,Integer total){
    	if(queryVO == null){
    		return Page.EMPTY_PAGE;
    	}
    	if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
    	return this.queryForPage("Shopext.selectByVO", queryVO, pageIndex, pageSize, total);
    }
           
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public void insert(Shopext record){
    	if(record==null)
    		return;
		super.insert("Shopext.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Shopext vo){
    	if(vo==null||vo.getShopid()==null)
    		return 0;
		int rows = super.update("Shopext.updateByPK", vo);
		return rows;
    }
    
    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public void save(Shopext vo){
    	if(vo==null||vo.getShopid()==null)
    		return;
    	Shopext dbvo = selectByPK(vo.getShopid());
		if(dbvo==null){
			this.insert(vo);
		}else{
			this.updateByPK(vo);
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long shopid){
    	if(shopid==null)
    		return 0;
    	int rows = super.delete("Shopext.deleteByPK", shopid);
		return rows;
    }
    
   
    /**
     * static spring getMethod
     */
     public static ShopextDao getInstance(){
    	 ShopextDao dao = (ShopextDao)BeanFactory.getBeanFactory().getBean("shopextDao");
         return dao;
     }
    
}
