package netTest.paper.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.paper.vo.Paperpatternratio;
import netTest.paper.dto.PaperpatternratioQuery;

public interface PaperpatternratioDao {
   
    /**
     * select some record by PK
     */
    public Paperpatternratio selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(PaperpatternratioQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(PaperpatternratioQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Paperpatternratio record);

    /**
     * update a record By PK
     */
    public int updateByPK(Paperpatternratio record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Paperpatternratio save(Paperpatternratio record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long paperid,Long questypeid,Long elementid,Short elementtype);
    
    /**
     * delete a record by Paperid
     */
    public int delByPaperid(Long paperid);
    
    /**
     * delete a record by Paperques pattern
     */
    public int deleteByQuesPattern(Long paperid,Long questypeid);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
