package netTest.paper.dao;

import java.util.List;

import netTest.paper.dto.PaperquesQuery;
import netTest.paper.vo.Paper;
import netTest.paper.vo.Paperques;
import netTest.wareques.vo.Question;

public interface PaperquesDao {
               
    /**
     * select some record by PK
     */
    public Paperques selectByPK(Long pk);
    
    /**
     * 根据试卷id和问题类型查询试卷题目
     * @param papre
     * @param questypeid
     * @return
     */
    public List<Paperques> qryByPaperPatt(Long paperid,Long questypeid);
    
    /**
     * 查询数目
     * @param queryVO
     * @return
     */
    public int countByVO(PaperquesQuery queryVO);
    
    /**
     * 根据题目题型questypeid更新试卷中改型题目的每题分值
     * @param quesid
     * @param num
     * @return
     */
    public int updateScoreByPatt(Long shopid,Long paperid,Long questypeid,Float paperquesscore);
    
    /**
     * 查询同一类型题目的需要计分的数目
     * @param queryVO
     * @return
     */
    public int qryOptnumByPatt(Long shopid,Long paperid,Long questypeid);
    
    /**
     * 返回子问题，例如:返回阅读理解的子题目
     * @param pid
     * @param paperquesscore
     * @return
     */
    public List<Question> selectByPid(Long pid, Float paperquesscore);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Paperques record);

    /**
     * update a record By PK
     */
    public int updateByPK(Paperques record);

	/**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Paperques save(Paperques record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List<Paperques> list);
    
    /**
     * select paperques by quesID
     */
    public Paperques qryPaperquesByQues(Long quesid, Long paperid);
    
    /**
     * select paper by quesID
     */
    public List<Paper> qryPaperByQues(List<Long> quesidlist, Long shopid);
	
}
