package platform.social.dao;

import java.util.List;

import platform.social.dto.CommentsQuery;
import platform.social.vo.Comments;
import commonTool.base.Page;


public interface CommentsDao {
   
    /**
     * select some record by PK
     */
    public Comments selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(CommentsQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(CommentsQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Comments record);

    /**
     * update a record By PK
     */
    public int updateByPK(Comments record);

    /**
     * 更新comment的子评论数目
     * @param pk
     * @param number
     */
    public void updateSubNum(Long pk, int number);
    
    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Comments save(Comments record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * delete all child comments of some comment
     */
    public int deleteChildByPK(Long parentid);
    
    public int deleteByObject(String objectid, String objecttype);
    
}
