package platform.social.dao;

import java.util.List;

import platform.social.dto.LeavemessageQuery;
import platform.social.vo.Leavemessage;

import commonTool.base.Page;


public interface LeavemessageDao {
   
    /**
     * select some record by PK
     */
    public Leavemessage selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(LeavemessageQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(LeavemessageQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Leavemessage record);

    /**
     * update a record By PK
     */
    public int updateByPK(Leavemessage record);
    
    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Leavemessage save(Leavemessage record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * delete all child
     */
    public int deleteChildByPK(Long parentid);
       
    /**
     * deleteBatch records by the String Array of PK
     */
//    public int deleteBatchByPK(String[] pkArray);
	
}
