package netTest.product.dao.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import netTest.bean.BeanFactory;
import netTest.product.dao.UserprodbuylogDao;
import netTest.product.dto.UserprodbuylogQuery;
import netTest.product.vo.Userprodbuylog;
import netTest.product.vo.Userproduct;

import org.apache.log4j.Logger;

import commonTool.base.BaseDao;
import commonTool.base.Page;
import commonTool.constant.CommonConstant;

public class UserprodbuylogDaoImpl extends BaseDao implements UserprodbuylogDao {

	static Logger log = Logger.getLogger(UserprodbuylogDaoImpl.class.getName());
	
    /**
     *
     */
    public UserprodbuylogDaoImpl() {
        super();
    }
  
        
    /**
     * select records by queryVO
     */
    public List selectByVO(UserprodbuylogQuery queryVO) {
		if(queryVO==null)
			return new ArrayList();
		List list = this.queryForList("Userprodbuylog.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(UserprodbuylogQuery queryVO,int pageIndex,int pageSize,Integer total) {
    	if(queryVO==null)
    		return Page.EMPTY_PAGE;
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "Userprodbuylog.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Userprodbuylog record) {
    	if(record==null||record.getUserproductid()==null)
    		return null;
		super.insert("Userprodbuylog.insert", record);
		return record.getUserproductid();
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List<Userprodbuylog> list) {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Userprodbuylog.insert", list);
       	return rows;
    }

    
    /**
     * 根据订单条目vo和用户产品id记录用户购买产品记录
     * @param itemVO
     * @param userproductid
     * @return
     */
    public boolean logUserProduct(List<Userproduct> usrprdList, Long orderid, Date happendate, Short action){
    	if(usrprdList==null||usrprdList.size()<1||happendate==null)
    		return false;
    	List<Userprodbuylog> insertList = new ArrayList<Userprodbuylog>();
    	for(Userproduct vo : usrprdList){
    		Userprodbuylog logVO = new Userprodbuylog();
        	logVO.setOrderid(orderid);
        	logVO.setProductbaseid(vo.getProductbaseid());
        	logVO.setProductname(vo.getProductname());
        	logVO.setShopid(vo.getShopid());
        	logVO.setUserid(vo.getUserid());
        	logVO.setUserproductid(vo.getUserproductid());
        	logVO.setHappendate(happendate);
        	logVO.setAction(action);
        	insertList.add(logVO);
    	}
    	
		this.insertBatch(insertList);
		return true;
    }
    
    
    /**
     * static spring getMethod
     */
     public static UserprodbuylogDao getInstance() {
         UserprodbuylogDao dao = (UserprodbuylogDao)BeanFactory.getBeanFactory().getBean("userprodbuylogDao");
         return dao;
     }
    
}
