package commonWeb.security.dao;

import java.util.List;
import java.util.Map;

import commonTool.base.Page;
import commonWeb.security.dto.MenusQuery;
import commonWeb.security.vo.Menus;

public interface MenusDao {
   
    /**
     * select some record by PK
     */
    public Menus selectByPK(Long pk,Long localeid);
    
    /**
     * select all records
     * @return
     */
    public List selectAll();
        
    /**
     * select records by queryVO
     */
    public List selectByVO(MenusQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(MenusQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * 查询用户可以查看道德菜单集合。
     * TODO 现在的实现是时时查询数据库，以后要改变这一实现
     * @param syscode
     * @param upId
     * @param userId
     * @param localeId
     * @param menutype
     * @return
     */
    public List selectForDisplay(String syscode,Long upId,Long userId,Long localeId,Long shopid);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Menus record);

    /**
     * update a record By PK
     */
    public int updateByPK(Menus record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Menus save(Menus record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) ;
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(MenusQuery queryVO);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list);
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public Map deleteBatchByPK(Long[] pkArray,Long localeid);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public Map deleteBatchByPK(String[] pkArray,Long localeid);
	
}
