package commonWeb.security.dao;

import java.util.List;

import commonTool.base.Page;
import commonWeb.security.dto.RolesvalueQuery;
import commonWeb.security.vo.Rolesvalue;

public interface RolesvalueDao {
   
    /**
     * select some record by PK
     */
    public Rolesvalue selectByPK(Long pk);
        
    /**
     * select records by queryVO
     */
    public List selectByVO(RolesvalueQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(RolesvalueQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Rolesvalue record);

    /**
     * update a record By PK
     */
    public int updateByPK(Rolesvalue record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Rolesvalue save(Rolesvalue record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception ;
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(RolesvalueQuery queryVO);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list);
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
