package commonWeb.security.dao;

import java.util.List;
import commonWeb.security.dto.RolesQuery;
import commonWeb.security.vo.Roles;

public interface RolesDao {
   
	public Roles selectByPK(Long pk);
    
    /**
     * select some record by PK and localeid
     */
    public Roles selectValueByPK(Long pk,Long localeid);
        
    /**
     * select all records
     * @return
     */
    public List selectAll();
        
    /**
     * select records by queryVO
     */
    public List selectByVO(RolesQuery queryVO);
    
    /**
     * 根据角色code查询角色id字符串，方便其他查询
     * @param rolecodeArr
     * @param syscode
     * @return
     */
    public String selRoleidStrByCode(String[] rolecodeArr, String syscode);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
    * @return list
     * @throws Exception
     */
    //public List selectByUserId(RolesQuery queryVO);
    
    /**
     * 选择某用户没有的Roles，以供选择，其中不包括用户已经具有的角色
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @return List
     * @throws Exception
     */
    public List selectRolesForUserAdd(RolesQuery queryVO);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Roles record);

    /**
     * update a record By PK
     */
    public int updateByPK(Roles record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Roles save(Roles record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception ;
    
//    /**
//     * delete records by queryVO
//     */
//    public int deleteByVO(RolesQuery queryVO);
//
//	/**
//     * insertBatch records of List
//     */
//    public int insertBatch(List list);
//    
//    /**
//     * updateBatch records of List
//     */
//    public int updateBatch(List list);
//
//    
//    /**
//     * deleteBatch records by the String Array of PK
//     */
//    public int deleteBatchByPK(String[] pkArray);
	
}
