package commonWeb.security.dao;

import java.util.List;

import commonWeb.security.vo.UserRole;

public interface UserRoleDao {
                   
    /**
     * select the user's roles by userid,shopid,syscode
     */
    public List<Long> selectUserRole(Long userid,Long shopid,String syscode);
    
    /**
     * 查询在商店中具有某种role的用户id列表
     */
    public List<Long> selectUserByShopRole(Long shopid, String roleidStr, String syscode);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(UserRole record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long userid, Long roleid, Long shopid, String syscode);
        
    /**
     * 一次插入多个用户角色记录，一般是：给一个用户插入多个角色或给一个角色分配多个用户
     * @param userIds
     * @param roleIds
     * @return
     */
    public int insertMoreBatch(Long[] userIds,Long[] roleIds, UserRole vo);
    
    /**
     * deleteBatch records by the List of vo
     */
    public int deleteBatchByPK(List list);
      
    /**
     * 查询传入的role中有哪些role下面有人员。返回有人员的role，其中用逗号隔开的返回结果。
     * @param roles
     * @return
     */
    public List<Long> selectUserUnderRole(Long roleid);
    
    public int deleteUserRoleInShop(Long userid, Long shopid, String syscode);
    
}
