package platform.user.dao;

import java.util.List;
import commonTool.base.Page;
import platform.user.vo.Accountvalidatetask;
import platform.user.dto.AccountvalidatetaskQuery;

public interface AccountvalidatetaskDao {
   
    /**
     * select some record by PK
     */
    public Accountvalidatetask selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(AccountvalidatetaskQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(AccountvalidatetaskQuery queryVO,int pageIndex,int pageSize);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Accountvalidatetask record);

    /**
     * update a record By PK
     */
    public int updateByPK(Accountvalidatetask record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Accountvalidatetask save(Accountvalidatetask record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
