package netTest.product.vo;

import java.util.Date;

import netTest.common.vo.NettestBaseVO;
import platform.logic.Container;

public class Coursepost extends NettestBaseVO implements Container{

    private Long id;

    private String caption;
    
    private String refobjecttype;
    
    private Long refobjectid;
    
    private Short generatetype;

    private Long creator;
    
    private String content = "";
    
    private String openurl;
    
    private Integer orderno;
    
    private Date createtime;
    
    private Date updatetime;
    
    
    
    public static final String ObjectType = "coursepost";
    
    // 1: course admin create it in page.  
    // 2: auto generated by another object. e.g: creating a new examination, may create this post
    public static final Short GenerateType_PageCreate = 1;
    public static final Short GenerateType_AutoCreate = 2;
    

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Long getCreator() {
        return creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getOpenurl() {
		return openurl;
	}

	public void setOpenurl(String openurl) {
		this.openurl = openurl;
	}
	
	public Integer getOrderno() {
		return orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	public String getRefobjecttype() {
		return refobjecttype;
	}

	public void setRefobjecttype(String refobjecttype) {
		this.refobjecttype = refobjecttype;
	}

	public Long getRefobjectid() {
		return refobjectid;
	}

	public void setRefobjectid(Long refobjectid) {
		this.refobjectid = refobjectid;
	}

	public Short getGeneratetype() {
		return generatetype;
	}

	public void setGeneratetype(Short generatetype) {
		this.generatetype = generatetype;
	}

	public Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Override
	protected String getObjectType() {
		return ObjectType;
	}

	public Long getContainerID() {
		return productbaseid;
	}

	public String getContainerType() {
		return ProductMini.ObjectType;
	}
	
	public boolean isSameShop(Long shopid){
		if(shopid!=null && shopid.equals(this.shopid)){
			return true;
		}else {
			return false;
		}
	}
	
}