package acegi.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import acegi.dao.CustorderDao;
import commonTool.constant.CommonConstant;
import acegi.vo.Custorder;
import acegi.dto.CustorderQuery;
import acegi.bean.BeanFactory;

public class CustorderDaoImpl extends BaseDao implements CustorderDao {

	static Logger log = Logger.getLogger(CustorderDaoImpl.class.getName());
	
    /**
     *
     */
    public CustorderDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Custorder selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Custorder record = (Custorder) this.queryForObject("Custorder.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("Custorder.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(CustorderQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("Custorder.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(CustorderQuery queryVO,int pageIndex,int pageSize){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Custorder.selectAll";
        else 
        	sqlStr = "Custorder.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Custorder record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Custorder.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Custorder record){
    	if(record==null||record.getOrderid()==null)
    		return 0;
		int rows = super.update("Custorder.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Custorder save(Custorder record){
    	if(record==null)
    		return null;
		if(record.getOrderid()==null||record.getOrderid().intValue()==0){
			Long pkValue = this.insert(record);
			record.setOrderid(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Custorder.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(CustorderQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("Custorder.deleteByVO",queryVO);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Custorder.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("Custorder.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("Custorder.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static CustorderDao getInstance(){
       	 CustorderDao dao = (CustorderDao)BeanFactory.getBeanFactory().getBean("custorderDao");
         return dao;
     }
    
}
