package acegi.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import acegi.dao.MenusvalueDao;
import commonTool.constant.CommonConstant;
import acegi.vo.Menusvalue;
import acegi.dto.MenusvalueQuery;
import acegi.bean.BeanFactory;

public class MenusvalueDaoImpl extends BaseDao implements MenusvalueDao {

	static Logger log = Logger.getLogger(MenusvalueDaoImpl.class.getName());
	
    /**
     *
     */
    public MenusvalueDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Menusvalue selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Menusvalue record = (Menusvalue) this.queryForObject("Menusvalue.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("Menusvalue.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(MenusvalueQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("Menusvalue.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(MenusvalueQuery queryVO,int pageIndex,int pageSize){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Menusvalue.selectAll";
        else 
        	sqlStr = "Menusvalue.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Menusvalue record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Menusvalue.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Menusvalue record){
    	if(record==null||record.getMenuvalueid()==null)
    		return 0;
		int rows = super.update("Menusvalue.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Menusvalue save(Menusvalue record){
    	if(record==null)
    		return null;
		if(record.getMenuvalueid()==null||record.getMenuvalueid().intValue()==0){
			Long pkValue = this.insert(record);
			record.setMenuvalueid(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Menusvalue.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(MenusvalueQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("Menusvalue.deleteByVO",queryVO);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Menusvalue.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("Menusvalue.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("Menusvalue.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static MenusvalueDao getInstance(){
       	 MenusvalueDao dao = (MenusvalueDao)BeanFactory.getBeanFactory().getBean("menusvalueDao");
         return dao;
     }
    
}
