package acegi.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import acegi.dao.Role_rescDao;
import commonTool.constant.CommonConstant;
import acegi.vo.Role_resc;
import acegi.dto.Role_rescQuery;
import acegi.bean.BeanFactory;

public class Role_rescDaoImpl extends BaseDao implements Role_rescDao {

	static Logger log = Logger.getLogger(Role_rescDaoImpl.class.getName());
	
    /**
     *
     */
    public Role_rescDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Role_resc selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Role_resc record = (Role_resc) this.queryForObject("Role_resc.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("Role_resc.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(Role_rescQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("Role_resc.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(Role_rescQuery queryVO,int pageIndex,int pageSize){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Role_resc.selectAll";
        else 
        	sqlStr = "Role_resc.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Role_resc record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Role_resc.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Role_resc record){
    	if(record==null||record.get{[#pkInMethod#]}()==null)
    		return 0;
		int rows = super.update("Role_resc.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Role_resc save(Role_resc record){
    	if(record==null)
    		return null;
		if(record.get{[#pkInMethod#]}()==null||record.get{[#pkInMethod#]}().intValue()==0){
			Long pkValue = this.insert(record);
			record.set{[#pkInMethod#]}(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Role_resc.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(Role_rescQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("Role_resc.deleteByVO",queryVO);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Role_resc.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("Role_resc.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("Role_resc.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static Role_rescDao getInstance(){
       	 Role_rescDao dao = (Role_rescDao)BeanFactory.getBeanFactory().getBean("role_rescDao");
         return dao;
     }
    
}
