package acegi.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import acegi.dao.UsersDao;
import commonTool.constant.CommonConstant;
import acegi.vo.Users;
import acegi.dto.UsersQuery;
import acegi.bean.BeanFactory;

public class UsersDaoImpl extends BaseDao implements UsersDao {

	static Logger log = Logger.getLogger(UsersDaoImpl.class.getName());
	
    /**
     *
     */
    public UsersDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Users selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Users record = (Users) this.queryForObject("Users.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("Users.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(UsersQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("Users.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(UsersQuery queryVO,int pageIndex,int pageSize){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Users.selectAll";
        else 
        	sqlStr = "Users.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Users record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Users.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Users record){
    	if(record==null||record.getId()==null)
    		return 0;
		int rows = super.update("Users.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Users save(Users record){
    	if(record==null)
    		return null;
		if(record.getId()==null||record.getId().intValue()==0){
			Long pkValue = this.insert(record);
			record.setId(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Users.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(UsersQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("Users.deleteByVO",queryVO);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Users.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("Users.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("Users.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static UsersDao getInstance(){
       	 UsersDao dao = (UsersDao)BeanFactory.getBeanFactory().getBean("usersDao");
         return dao;
     }
    
}
