package acegi.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import acegi.dao.User_roleDao;
import commonTool.constant.CommonConstant;
import acegi.vo.User_role;
import acegi.dto.User_roleQuery;
import acegi.bean.BeanFactory;

public class User_roleDaoImpl extends BaseDao implements User_roleDao {

	static Logger log = Logger.getLogger(User_roleDaoImpl.class.getName());
	
    /**
     *
     */
    public User_roleDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public User_role selectByPK(Long pk){
    	if(pk==null)
    		return null;
		User_role record = (User_role) this.queryForObject("User_role.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("User_role.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(User_roleQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("User_role.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(User_roleQuery queryVO,int pageIndex,int pageSize){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "User_role.selectAll";
        else 
        	sqlStr = "User_role.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(User_role record){
    	if(record==null)
    		return null;
		return (Long)super.insert("User_role.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(User_role record){
    	if(record==null||record.getRoleId()==null)
    		return 0;
		int rows = super.update("User_role.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public User_role save(User_role record){
    	if(record==null)
    		return null;
		if(record.getRoleId()==null||record.getRoleId().intValue()==0){
			Long pkValue = this.insert(record);
			record.setRoleId(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("User_role.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(User_roleQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("User_role.deleteByVO",queryVO);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("User_role.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("User_role.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("User_role.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static User_roleDao getInstance(){
       	 User_roleDao dao = (User_roleDao)BeanFactory.getBeanFactory().getBean("user_roleDao");
         return dao;
     }
    
}
