package netTest.orguser.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.orguser.dto.OrguserQuery;
import netTest.orguser.vo.Orguser;

public interface OrguserDao {
   
    /**
     * select some record by PK
     */
    public Orguser selectByPK(Long pk) ;
    
    /**
     * 查询出该用户的综合信息，包括用户表等信息，但不包括用户扩展信息等
     */
    public Orguser qryOrguserByPK(Long pk) ;
        
    /**
     * select records by queryVO
     */
    public List selectByVO(OrguserQuery queryVO) ;
    
    /**
     * 查询user对应的org信息
     */
    public Orguser selectOrgForUser(Long userid, Long shopid);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(OrguserQuery queryVO,int pageIndex,int pageSize,Integer total) ;
    
    /**
     * 查询用户的分页详细信息，来自usershop,orgbase,user
     * @param queryVO
     * @param pageIndex
     * @param pageSize
     * @return
     * @throws Exception
     */
    public Page selectUserByVOPage(OrguserQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Orguser record);

    
    /**
     * 更新传入用户的单位，一般用于人员转单位
     * @param useridStr
     * @param newDeptid
     * @return
     */
    public int updateDept(Long userid,Long oldDeptid, Long newDeptid, String orgpath);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) ;
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list);
    
    	
    /**
     * 根据用户和商店删除人员信息，可以删除单位人员和小组人员信息
     * @param userid
     * @param shopid
     * @return
     */
    public int delOrguser(Long userid,Long shopid);

    
}
