package netTest.order.dao;

import java.util.Date;
import java.util.List;

import netTest.order.dto.CustorderQuery;
import netTest.order.vo.Custorder;
import commonTool.base.Page;

public interface CustorderDao {
   
    /**
     * select some record by PK
     */
    public Custorder selectByPK(Long pk);

    /**
     * 查询完整的订单信息，包括：订单的审批和说明内容
     */
    public Custorder qryWholeByPK(Long pk);
    
    /**
     * select records by queryVO
     */
    public List selectByVO(CustorderQuery queryVO);
    
    /**
     * 查询数量
     */
    public Integer selectCount(CustorderQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @
     */
    public Page selectByVOPage(CustorderQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Custorder record);

    /**
     * update a record By PK
     */
    public int updateByPK(Custorder record);
        
    /**
     * 更改订单的支付状态
     * @param orderid
     * @param paystatus
     * @return
     * @
     */
    public boolean updatePayStatus(Long orderid,Short paystatus) ;
    
    /**
     * 更改订单状态
     * @param orderid
     * @param paystatus
     * @return
     * @
     */
    public boolean updateOrderStatus(Long orderid, Short orderstatus, Date date, String appnotes, Long operatorid) ;

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @
     */
    public Custorder save(Custorder record)  ;
    
    /**
     * 生成订单编码，如果长度小于10位则在前面补0凑够10位，如果大于10位直接返回
     * @return
     * @
     */
    public String geneOrderCode() ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk)  ;
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list)  ;
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list)  ;
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
    
    /**
     * select orderExt info by orderid
     */
    public Custorder qryOrderExtByPK(Long orderid);
    
    /**
     * update a order ext info by pk
     */
    public int updateOrderExt(Custorder record);
	
}
