package netTest.wareques.dao;

import java.util.List;

import netTest.wareques.vo.Question;

public interface QuesBaseDaoInf {

    /**
     * select some record by PK
     */
    public Question selectByPK(Long pk);
    
    /**
     * 仅仅查询基本信息
     * @param pk
     * @return
     */
    public Question selectBasicByPK(Long pk);
    
    /**
     * 根据父题目id查询所有的子题目
     * @param pid
     * @return
     */
    public List<Question> selectByPid(Long pid);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Question record);

    /**
     * update a record By PK
     */
    public int updateByPK(Question record);
    
    /**
     * 更新问题的文件链接地址
     * @param quesid
     * @param fileurl
     * @return
     */
    public boolean updateFileurl(Long quesid,String fileurl);

	/**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Question save(Question record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * 根据主问题id删除其下的子问题，包括Questionitem,Quesanswer,Question
     * @param pid
     * @return
     */
    public int delSubquesByPid(Long pid);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
    
    /**
     * 更新题目的子题目个数quesOptNum字段
     * @param quesid
     * @param num
     * @return
     */
    public int updateQuesOptNum(Long quesid,int num);
	
}
