package netTest.wareques.dao;

import java.util.List;

import netTest.wareques.vo.Questionitem;

public interface QuestionitemDao {
   
    /**
     * select some record by PK
     */
    public Questionitem selectByPK(Long pk);
    
    /**
     * select records by queryVO
     */
    public List selectByVO(Questionitem queryVO);
    
    /**
     * select records by quesid
     */
    public List selectByQues(Long quesid,Long shopid);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Questionitem record);
    
    /**
     * 得到字段quesItemFlag的下一个序列值，通过查询表SEQ_QuesItemFlag得到
     * @return
     */
    public String qryItemFlagSEQ();

    /**
     * update a record By PK
     */
    public int updateByPK(Questionitem record);
    
    /**
     * 更新问题选项的文件链接地址
     * @param quesid
     * @param fileurl
     * @return
     */
    public boolean updateFileurl(Long itemid,String fileurl);
    
    /**
     * 更换两个题目的题目选项的disorder
     * @param vo
     * @param type:1代表向上移动(disorder变小)，2代表向下移动
     * @return
     */
    public boolean switDisorderQues(Questionitem vo,int type);

    /**
     * 根据子题目选项id和显示序号查询比指定disorder略大的显示序号
     * 如果disorder为空，则查询所属的quesid下的子选项中最大的显示号disorder
     * @param quesid
     * @param disorder
     * @return
     */
    public Integer qryLargerDisorder(Long quesid,Integer disorder);
    
	/**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Questionitem save(Questionitem record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * 根据问题id删除该问题下的答案选项
     * @param quesid
     * @return
     */
    public int deleteByQuesid(Long quesid);
    
    /**
     * 根据问题id和问题显示顺序disorder删除题目，主要是对完形填空的答案选项
     * @param quesid
     * @return
     */
    public int delByQuesidOrder(Long quesid,Integer disorder);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
