package netTest.wareques.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.wareques.vo.Questypeshop;
import netTest.wareques.dto.QuestypeshopQuery;

public interface QuestypeshopDao {
   
    /**
     * select some record by PK
     */
    public Questypeshop selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(QuestypeshopQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(QuestypeshopQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Questypeshop record);

    /**
     * update a record By PK
     */
    public int updateByPK(Questypeshop record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Questypeshop save(Questypeshop record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
