package netTest.wareques.dao;

import java.util.List;
import java.util.Map;

import netTest.wareques.vo.Quesanswer;

import commonTool.base.Page;

public interface QuesanswerDao {
   
    /**
     * select some record by PK
     */
    public Quesanswer selectByPK(Long pk);
    
    /**
     * select records by queryVO
     */
    public List selectByVO(Quesanswer queryVO);
    
    /**
     * select records by pk string, joined by comma
     */
    public Map<Long, Quesanswer> selectByPkStr(String selectByPkStr);

    /**
     * 保存，不存在就插入，否则更新
     * @param vo
     * @return
     */
    public int save(Quesanswer vo);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Quesanswer record);

    /**
     * update a record By PK
     */
    public int updateByPK(Quesanswer record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
