package netTest.wareques.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.wareques.vo.Quesdifficult;
import netTest.wareques.dto.QuesdifficultQuery;

public interface QuesdifficultDao {
   
    /**
     * select some record by PK
     */
    public Quesdifficult selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(QuesdifficultQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(QuesdifficultQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Quesdifficult record);

    /**
     * update a record By PK
     */
    public int updateByPK(Quesdifficult record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Quesdifficult save(Quesdifficult record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception ;
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(QuesdifficultQuery queryVO);

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
