package platform.shop.dao;

import java.util.List;

import platform.shop.vo.Prodcateshop;


public interface ProdcateshopDao {
            
    /**
     * select records by queryVO
     */
    public List selectByShop(Long shopid, Long localeid);
    
    /**
     * 查找该目录的下一级目录的子目录数
     * @param 
     * @return
     */
    public List getChildNodes(Long pid, Long shopid, Long localeid, String syscode);
    
    /**
     * 查询某个目录夹是否已经存在商店的目录夹中了，即判断商店是否已经选择了该商品目录
     * @param 
     * @return true:已经存在，false:不存在
     */
    public boolean existsCate(Long categroyid, Long shopid, String syscode);
    
    /**
     * 查询某个目录夹下是否有商店选择的子目录
     * @param 
     * @return true:已经存在，false:不存在
     */
    public boolean existChildNode(Long pid, Long shopid, String syscode);
    
    /**
     * 查询某个目录夹下是否有商店的产品
     * @param 
     * @return true:已经存在，false:不存在
     */
    public boolean cateExistProd(Long categoryid, Long shopid, String syscode);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Prodcateshop record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long shopid, Long categoryid, String syscode);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List<Prodcateshop> list, Long shopid);
    
	
}
