package platform.shop.dao;

import java.util.List;

import platform.shop.vo.Shoplicense;

public interface ShoplicenseDao {
   
    /**
     * select some record by PK
     */
    public Shoplicense selectByPK(Long shopid, String syscode, String resourcecode);
            
    /**
     * select records by shop
     */
    public List selectByShop(Long shopid, String syscode);
    
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shoplicense record);

    /**
     * update a record By PK
     */
    public int updateByPK(Shoplicense record);
    
    /**
     * 修改shop的license使用数据，累计的增加或减少
     */
    public boolean updateLicenseUsageSum(Long shopid, String syscode, String resourcecode, Long size);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Shoplicense save(Shoplicense record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long shopid, String syscode, String resourcecode);
    
	/**
     * 根据商店和系统code删除，shopid为必须的
     */
    public int deleteByShop(Long shopid, String syscode);
	
}
