package netTest.exercise.dao.impl;

import java.util.ArrayList;
import java.util.List;

import netTest.bean.BeanFactory;
import netTest.exercise.dao.ExerquestypeDao;
import netTest.exercise.dto.ExerquestypeQuery;
import netTest.exercise.vo.Exerquestype;

import org.apache.log4j.Logger;

import commonTool.base.BaseDao;
import commonTool.base.Page;
import commonTool.constant.CommonConstant;

public class ExerquestypeDaoImpl extends BaseDao implements ExerquestypeDao {

	static Logger log = Logger.getLogger(ExerquestypeDaoImpl.class.getName());
	
    /**
     *
     */
    public ExerquestypeDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Exerquestype selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Exerquestype record = (Exerquestype) this.queryForObject("Exerquestype.selectByPK", pk);
		return record;
    }
           
    /**
     * select records by queryVO
     */
    public List selectByVO(ExerquestypeQuery queryVO){
		if(queryVO==null)
			return new ArrayList();
		List list = this.queryForList("Exerquestype.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select records by exercise id
     */
    public List qryByExerid(Long exerid){
		if(exerid==null)
			return new ArrayList();
		List list = this.queryForList("Exerquestype.qryByExerid", exerid);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(ExerquestypeQuery queryVO,int pageIndex,int pageSize,Integer total){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        Page page = null;
        String sqlStr = "";
        if(queryVO==null){
        	page = Page.EMPTY_PAGE;
        } else {
        	sqlStr = "Exerquestype.selectByVO";
        	page = queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
        }
        return page;
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Exerquestype record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Exerquestype.insert", record);
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Exerquestype.insert", list);
       	return rows;
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Exerquestype record){
    	if(record==null||record.getPatternid()==null)
    		return 0;
		int rows = super.update("Exerquestype.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Exerquestype save(Exerquestype record){
    	if(record==null)
    		return null;
		if(record.getPatternid()==null||record.getPatternid().intValue()==0){
			Long pkValue = this.insert(record);
			record.setPatternid(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Exerquestype.deleteByPK", pk);
		return rows;
    }
    
    /**
     * 删除该次练习的所有用户答案
     */
    public int deleteByExer(Long exerid){
    	if(exerid==null)
    		return 0;
		int rows = super.delete("Exerquestype.deleteByExer", exerid);
		return rows;
    }
    
    
    /**
     * static spring getMethod
     */
     public static ExerquestypeDao getInstance(){
       	 ExerquestypeDao dao = (ExerquestypeDao)BeanFactory.getBeanFactory().getBean("exerquestypeDao");
         return dao;
     }
    
}
