package netTest.exam.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.exam.vo.Testdept;
import netTest.exam.dto.TestdeptQuery;

public interface TestdeptDao {
   
    /**
     * select some record by PK
     */
    public Testdept selectByPK(Long pk);
    
    /**
     * 查询考试的统计信息单位记录，记录了本次考试的总的统计情况
     * @return
     */
    public Testdept selSatTestDept(Long testid);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(TestdeptQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(TestdeptQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * 统计考试单位的平均分
     */
    public int satDeptAvescore(Long testid,Long shopid);
    
    /**
     * 查询设置考试中有哪些单位是本次考试中已经有的。用于过滤考试单位。
     * 返回的是单位的串，用','隔开
     * @param testid
     * @param deptIdstr
     * @param shopid
     * @return
     */
//    public String qryJoinTestdepts(Long testid,String deptIdstr,Long shopid);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Testdept record);

    /**
     * update a record By PK
     */
    public int updateByPK(Testdept record);
    
    
    /**
     * 更新考试的人员数量信息，只需更新type=1的统计单位信息
     * 
     */
    public int updateExamNumSat(Testdept record);
    
    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Testdept save(Testdept record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * delete a record by Test
     */
    public int deleteByTest(Long testid,Long shopid);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
	
}
