package platform.vo;

import java.util.Date;

public class Costrecord {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Long costrecordid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Long baseaccountid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.objectID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Long objectid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.accountType
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Short accounttype;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.needPayTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Date needpaytime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.payTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Date paytime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.totalCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Double totalcost;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.isPay
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Short ispay;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.isCurCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private Short iscurcost;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column costrecord.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    private String costdisc;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.costRecordID
     * @return  the value of costrecord.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Long getCostrecordid() {
	return costrecordid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.costRecordID
     * @param costrecordid  the value for costrecord.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setCostrecordid(Long costrecordid) {
	this.costrecordid = costrecordid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.baseAccountID
     * @return  the value of costrecord.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Long getBaseaccountid() {
	return baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.baseAccountID
     * @param baseaccountid  the value for costrecord.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setBaseaccountid(Long baseaccountid) {
	this.baseaccountid = baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.objectID
     * @return  the value of costrecord.objectID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Long getObjectid() {
	return objectid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.objectID
     * @param objectid  the value for costrecord.objectID
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setObjectid(Long objectid) {
	this.objectid = objectid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.accountType
     * @return  the value of costrecord.accountType
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Short getAccounttype() {
	return accounttype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.accountType
     * @param accounttype  the value for costrecord.accountType
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setAccounttype(Short accounttype) {
	this.accounttype = accounttype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.needPayTime
     * @return  the value of costrecord.needPayTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Date getNeedpaytime() {
	return needpaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.needPayTime
     * @param needpaytime  the value for costrecord.needPayTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setNeedpaytime(Date needpaytime) {
	this.needpaytime = needpaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.payTime
     * @return  the value of costrecord.payTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Date getPaytime() {
	return paytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.payTime
     * @param paytime  the value for costrecord.payTime
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setPaytime(Date paytime) {
	this.paytime = paytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.totalCost
     * @return  the value of costrecord.totalCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Double getTotalcost() {
	return totalcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.totalCost
     * @param totalcost  the value for costrecord.totalCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setTotalcost(Double totalcost) {
	this.totalcost = totalcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.isPay
     * @return  the value of costrecord.isPay
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Short getIspay() {
	return ispay;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.isPay
     * @param ispay  the value for costrecord.isPay
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setIspay(Short ispay) {
	this.ispay = ispay;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.isCurCost
     * @return  the value of costrecord.isCurCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public Short getIscurcost() {
	return iscurcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.isCurCost
     * @param iscurcost  the value for costrecord.isCurCost
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setIscurcost(Short iscurcost) {
	this.iscurcost = iscurcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column costrecord.costDisc
     * @return  the value of costrecord.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public String getCostdisc() {
	return costdisc;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column costrecord.costDisc
     * @param costdisc  the value for costrecord.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:05 CST 2008
     */
    public void setCostdisc(String costdisc) {
	this.costdisc = costdisc;
    }
}