package platform.vo;

import java.util.Date;

public class Shopcosrecdet {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.shopCosRecDetID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long shopcosrecdetid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long costrecordid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long baseaccountid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.shopID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long shopid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.functionCode
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long functioncode;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.systemID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private String systemid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.functionName
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private String functionname;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.payType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Short paytype;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.payTime
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Date paytime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.cost
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Long cost;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.isPay
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Short ispay;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.costType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private Short costtype;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column shopcosrecdet.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    private String costdisc;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.shopCosRecDetID
     * @return  the value of shopcosrecdet.shopCosRecDetID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getShopcosrecdetid() {
	return shopcosrecdetid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.shopCosRecDetID
     * @param shopcosrecdetid  the value for shopcosrecdet.shopCosRecDetID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setShopcosrecdetid(Long shopcosrecdetid) {
	this.shopcosrecdetid = shopcosrecdetid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.costRecordID
     * @return  the value of shopcosrecdet.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getCostrecordid() {
	return costrecordid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.costRecordID
     * @param costrecordid  the value for shopcosrecdet.costRecordID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setCostrecordid(Long costrecordid) {
	this.costrecordid = costrecordid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.baseAccountID
     * @return  the value of shopcosrecdet.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getBaseaccountid() {
	return baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.baseAccountID
     * @param baseaccountid  the value for shopcosrecdet.baseAccountID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setBaseaccountid(Long baseaccountid) {
	this.baseaccountid = baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.shopID
     * @return  the value of shopcosrecdet.shopID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getShopid() {
	return shopid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.shopID
     * @param shopid  the value for shopcosrecdet.shopID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setShopid(Long shopid) {
	this.shopid = shopid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.functionCode
     * @return  the value of shopcosrecdet.functionCode
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getFunctioncode() {
	return functioncode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.functionCode
     * @param functioncode  the value for shopcosrecdet.functionCode
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setFunctioncode(Long functioncode) {
	this.functioncode = functioncode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.systemID
     * @return  the value of shopcosrecdet.systemID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public String getSystemid() {
	return systemid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.systemID
     * @param systemid  the value for shopcosrecdet.systemID
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setSystemid(String systemid) {
	this.systemid = systemid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.functionName
     * @return  the value of shopcosrecdet.functionName
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public String getFunctionname() {
	return functionname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.functionName
     * @param functionname  the value for shopcosrecdet.functionName
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setFunctionname(String functionname) {
	this.functionname = functionname;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.payType
     * @return  the value of shopcosrecdet.payType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Short getPaytype() {
	return paytype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.payType
     * @param paytype  the value for shopcosrecdet.payType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setPaytype(Short paytype) {
	this.paytype = paytype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.payTime
     * @return  the value of shopcosrecdet.payTime
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Date getPaytime() {
	return paytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.payTime
     * @param paytime  the value for shopcosrecdet.payTime
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setPaytime(Date paytime) {
	this.paytime = paytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.cost
     * @return  the value of shopcosrecdet.cost
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Long getCost() {
	return cost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.cost
     * @param cost  the value for shopcosrecdet.cost
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setCost(Long cost) {
	this.cost = cost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.isPay
     * @return  the value of shopcosrecdet.isPay
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Short getIspay() {
	return ispay;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.isPay
     * @param ispay  the value for shopcosrecdet.isPay
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setIspay(Short ispay) {
	this.ispay = ispay;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.costType
     * @return  the value of shopcosrecdet.costType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public Short getCosttype() {
	return costtype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.costType
     * @param costtype  the value for shopcosrecdet.costType
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setCosttype(Short costtype) {
	this.costtype = costtype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column shopcosrecdet.costDisc
     * @return  the value of shopcosrecdet.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public String getCostdisc() {
	return costdisc;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column shopcosrecdet.costDisc
     * @param costdisc  the value for shopcosrecdet.costDisc
     * @abatorgenerated  Sat Mar 15 18:47:06 CST 2008
     */
    public void setCostdisc(String costdisc) {
	this.costdisc = costdisc;
    }
}