package netTest.orguser.dao.impl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import commonTool.constant.CommonConstant;
import netTest.orguser.dao.OrglevelDao;
import netTest.orguser.dto.OrglevelQuery;
import netTest.orguser.vo.Orglevel;
import netTest.bean.BeanFactory;

public class OrglevelDaoImpl extends BaseDao implements OrglevelDao {

	static Logger log = Logger.getLogger(OrglevelDaoImpl.class.getName());
	
    /**
     *
     */
    public OrglevelDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Orglevel selectByPK(Long pk) throws Exception {
    	if(pk==null)
    		return null;
        try {
			Orglevel record = (Orglevel) this.queryForObject("Orglevel.selectByPK", pk);
			return record;
		} catch (Exception e) {
			log.error("OrglevelDaoImpl主键查询selectByPK时出错误!", e);
			throw e ;
		}
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll() throws Exception {
    	try {
			List list = this.queryForList("Orglevel.selectAll", null);
			return list;
		} catch (Exception e) {
			log.error("OrglevelDaoImpl的selectAll时出错误!", e);
			throw e ;
		}
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(OrglevelQuery queryVO) throws Exception {
        try {
			if(queryVO==null)
				return selectAll();
			List list = this.queryForList("Orglevel.selectByVO", queryVO);
			return list;
        } catch (Exception e) {
			log.error("OrglevelDaoImpl的selectByVO时出错误!", e);
			throw e ;
		}
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(OrglevelQuery queryVO,int pageIndex,int pageSize,Integer total) throws Exception {
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Orglevel.selectAll";
        else 
        	sqlStr = "Orglevel.selectByVO";
        try{
	        return queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
        }catch(Exception e) {
            log.error("OrglevelDaoImpl分页查询selectByVOPage时出错误!", e);
			throw e ;
        }
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Orglevel record) throws Exception {
    	if(record==null)
    		return null;
        try {
			return (Long)super.insert("Orglevel.insert", record);
        }catch(Exception e) {
            log.error("OrglevelDaoImpl插入insert时出错误!", e);
			throw e ;
        }
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Orglevel record) throws Exception {
    	if(record==null||record.getOrglevelid()==null)
    		return 0;
        try {
			int rows = super.update("Orglevel.updateByPK", record);
			return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl更新updateByPK时出错误!", e);
			throw e ;
        }
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Orglevel save(Orglevel record) throws Exception {
    	if(record==null)
    		return null;
    	try {
			if(record.getOrglevelid()==null||record.getOrglevelid().intValue()==0){
				Long pkValue = this.insert(record);
				record.setOrglevelid(pkValue);
				return record;
			}else{
				this.updateByPK(record);
				return record;
			}
		} catch (RuntimeException e) {
			log.error("OrglevelDaoImpl保存save时出错误!", e);
			throw e ;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception {
    	if(pk==null)
    		return 0;
        try {
			int rows = super.delete("Orglevel.deleteByPK", pk);
			return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl删除deleteByPK时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(OrglevelQuery queryVO) throws Exception {
    	if(queryVO==null)
    		return 0;
        try {
			int rows = super.delete("Orglevel.deleteByVO",queryVO);
			return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl删除deleteByVO时出错误!", e);
			throw e ;
        }
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.insertBatch("Orglevel.insert", list);
        	return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl批量新增insertBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.updateBatch("Orglevel.updateByPK", list);
        	return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl批量修改updateBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.deleteBatch("Orglevel.deleteByPK", pkArray);
        	return rows;
        }catch(Exception e) {
            log.error("OrglevelDaoImpl删除deleteBatchByPK(Long[] pkArray)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
    	try {
			for(int i=0;i<pkArray.length;i++){
				if(pkArray[i]!=null)
					arrs[i] = new Long(Long.parseLong(pkArray[i]));
			}
			rows = this.deleteBatchByPK(arrs);
			return rows;
		} catch (NumberFormatException e) {
			log.error("OrglevelDaoImpl删除deleteBatchByPK(String[] pkArray)时出现转换错�?!", e);
			throw new Exception("NumberFormatException：from String to Long!") ;
		}catch(Exception e) {
            log.error("OrglevelDaoImpl删除deleteBatchByPK(String[] pkArray)时出错误!", e);
			throw e ;
        }
    	
    }
    
    /**
     * static spring getMethod
     */
     public static OrglevelDao getInstance() {
       	 OrglevelDao dao = (OrglevelDao)BeanFactory.getBeanFactory().getBean("orglevelDaoProxy");
         return dao;
     }
    
}
