package netTest.exercise.dao;

import java.util.Date;
import java.util.List;

import netTest.exercise.dto.ExerciseQuery;
import netTest.exercise.vo.Exercise;
import commonTool.base.Page;

public interface ExerciseDao {
   
	public List<Exercise> selectExerByProd(Long productid, Long contentcateid);
	
    /**
     * select some record by PK
     */
    public Exercise selectByPK(Long pk);
    
    /**
     * select records by queryVO
     */
    public List selectByVO(ExerciseQuery queryVO);
        
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Exercise record);

    /**
     * update a record By PK
     */
    public int updateByPK(Exercise record);
        
    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Exercise save(Exercise record);

    /**
     * 删除试卷包括试卷属性，试卷属性，试卷子题目，试卷试题答案表，试卷题型表，试卷题型比例表，引用试卷题目
     * @param pk:试卷id
     */
    public int deleteByPK(Long pk);
    
//	/**
//     * insertBatch records of List
//     */
//    public int insertBatch(List list);
//    
//    /**
//     * deleteBatch records by the String Array of PK
//     */
//    public int deleteBatchByPK(String[] pkArray);
    
	
}
