package netTest.exercise.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.exercise.vo.Exerquestype;
import netTest.exercise.dto.ExerquestypeQuery;

public interface ExerquestypeDao {
   
    /**
     * select some record by PK
     */
    public Exerquestype selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(ExerquestypeQuery queryVO);
    
    /**
     * select records by exercise id
     */
    public List qryByExerid(Long exerid);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(ExerquestypeQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Exerquestype record);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);

    /**
     * update a record By PK
     */
    public int updateByPK(Exerquestype record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Exerquestype save(Exerquestype record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * 删除该次练习的所有用户答案
     */
    public int deleteByExer(Long exerid);
    
	
}
