package netTest.exercise.dao;

import java.util.List;
import commonTool.base.Page;
import netTest.exercise.vo.Exeruser;
import netTest.exercise.dto.ExeruserQuery;

public interface ExeruserDao {
   
    /**
     * select some record by PK
     */
    public Exeruser selectByPK(Long pk);
    
    /**
     * select some record by exerid and user
     */
    public Exeruser selectByLogicPK(Long exerid, Long userid);
    
    /**
     * 查询所有参加某次练习的所有用户
     */
    public Page selectExerUser(ExeruserQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @throws Exception
     */
    public List<Exeruser> selectMyExerPage(ExeruserQuery queryVO);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Exeruser record);

    /**
     * update a record By PK
     */
    public int updateByPK(Exeruser record);
    
    /**
     * 根据userid和exerid更新Exeruser
     */
    public int updateByLogicPK(Exeruser record, Long userid, Long exerid);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Exeruser save(Exeruser record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * 删除练习人员
     * @param exerid
     * @return
     */
    public int deleteByExer(Long exerid);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray);
	
}
