package commonWeb.security.dao.impl;

import java.util.List;

import org.apache.log4j.Logger;

import commonTool.base.BaseDao;
import commonTool.base.Page;
import commonTool.constant.CommonConstant;
import commonWeb.security.bean.BeanFactory;
import commonWeb.security.dao.ResourcesvalueDao;
import commonWeb.security.dto.ResourcesvalueQuery;
import commonWeb.security.vo.Resourcesvalue;

public class ResourcesvalueDaoImpl extends BaseDao implements ResourcesvalueDao {

	static Logger log = Logger.getLogger(ResourcesvalueDaoImpl.class.getName());
	
    /**
     *
     */
    public ResourcesvalueDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Resourcesvalue selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Resourcesvalue record = (Resourcesvalue) this.queryForObject("Resourcesvalue.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll(){
		List list = this.queryForList("Resourcesvalue.selectAll", null);
		return list;
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ResourcesvalueQuery queryVO){
		if(queryVO==null)
			return selectAll();
		List list = this.queryForList("Resourcesvalue.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(ResourcesvalueQuery queryVO,int pageIndex,int pageSize,Integer total){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Resourcesvalue.selectAll";
        else 
        	sqlStr = "Resourcesvalue.selectByVO";
        return queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Resourcesvalue record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Resourcesvalue.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Resourcesvalue record){
    	if(record==null||record.getRescvalueid()==null)
    		return 0;
		int rows = super.update("Resourcesvalue.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Resourcesvalue save(Resourcesvalue record){
    	if(record==null)
    		return null;
		if(record.getRescvalueid()==null||record.getRescvalueid().intValue()==0){
			Long pkValue = this.insert(record);
			record.setRescvalueid(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Resourcesvalue.deleteByPK", pk);
		return rows;
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(ResourcesvalueQuery queryVO){
    	if(queryVO==null)
    		return 0;
		int rows = super.delete("Resourcesvalue.deleteByVO",queryVO);
		return rows;
    }
    
    /**
     * 根据菜单国家语言设置表的id来删除资源表中的相应信息
     * @param menuvalueid
     * @return
     */
    public int delByMenuValueID(Long menuvalueid){
    	if(menuvalueid==null)
    		return 0;
		int rows = super.delete("Resourcesvalue.delByMenuValueID", menuvalueid);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Resourcesvalue.insert", list);
       	return rows;
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.updateBatch("Resourcesvalue.updateByPK", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
       	rows = super.deleteBatch("Resourcesvalue.deleteByPK", pkArray);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = this.deleteBatchByPK(arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static ResourcesvalueDao getInstance(){
       	 ResourcesvalueDao dao = (ResourcesvalueDao)BeanFactory.getBeanFactory().getBean("resourcesvalueDao");
         return dao;
     }
    
}
