package netTest.wareques.dao.impl;

import java.util.ArrayList;
import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import netTest.wareques.dao.QuestypeshopDao;
import commonTool.constant.CommonConstant;
import netTest.wareques.vo.Questypeshop;
import netTest.wareques.dto.QuestypeshopQuery;
import netTest.bean.BeanFactory;

public class QuestypeshopDaoImpl extends BaseDao implements QuestypeshopDao {

	static Logger log = Logger.getLogger(QuestypeshopDaoImpl.class.getName());
	
    /**
     *
     */
    public QuestypeshopDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Questypeshop selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Questypeshop record = (Questypeshop) this.queryForObject("Questypeshop.selectByPK", pk);
		return record;
    }
           
    /**
     * select records by queryVO
     */
    public List selectByVO(QuestypeshopQuery queryVO){
		if(queryVO==null)
			return new ArrayList();
		List list = this.queryForList("Questypeshop.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(QuestypeshopQuery queryVO,int pageIndex,int pageSize,Integer total){
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        Page page = null;
        String sqlStr = "";
        if(queryVO==null){
        	page = Page.EMPTY_PAGE;
        } else {
        	sqlStr = "Questypeshop.selectByVO";
        	page = queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
        }
        return page;
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Questypeshop record){
    	if(record==null)
    		return null;
		return (Long)super.insert("Questypeshop.insert", record);
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Questypeshop record){
    	if(record==null||record.getQuestypeid()==null)
    		return 0;
		int rows = super.update("Questypeshop.updateByPK", record);
		return rows;
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Questypeshop save(Questypeshop record){
    	if(record==null)
    		return null;
		if(record.getQuestypeid()==null||record.getQuestypeid().intValue()==0){
			Long pkValue = this.insert(record);
			record.setQuestypeid(pkValue);
    		return record;
		}else{
			this.updateByPK(record);
			return record;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk){
    	if(pk==null)
    		return 0;
		int rows = super.delete("Questypeshop.deleteByPK", pk);
		return rows;
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list){
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
       	rows = super.insertBatch("Questypeshop.insert", list);
       	return rows;
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray){
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
		for(int i=0;i<pkArray.length;i++){
			if(pkArray[i]!=null)
				arrs[i] = new Long(Long.parseLong(pkArray[i]));
		}
		rows = super.deleteBatch("Questypeshop.deleteByPK", arrs);
		return rows;
    }
    
    /**
     * static spring getMethod
     */
     public static QuestypeshopDao getInstance(){
       	 QuestypeshopDao dao = (QuestypeshopDao)BeanFactory.getBeanFactory().getBean("questypeshopDao");
         return dao;
     }
    
}
