package platform.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import platform.dao.CostrecordDao;
import commonTool.constant.CommonConstant;
import platform.vo.Costrecord;
import platform.dto.CostrecordQuery;
import platform.bean.BeanFactory;

public class CostrecordDaoImpl extends BaseDao implements CostrecordDao {

	static Logger log = Logger.getLogger(CostrecordDaoImpl.class.getName());
	
    /**
     *
     */
    public CostrecordDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Costrecord selectByPK(Long pk){
    	if(pk==null)
    		return null;
		Costrecord record = (Costrecord) this.queryForObject("Costrecord.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll() throws Exception {
    	try {
			List list = this.queryForList("Costrecord.selectAll", null);
			return list;
		} catch (Exception e) {
			log.error("CostrecordDaoImpl的selectAll时出错误!", e);
			throw e ;
		}
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(CostrecordQuery queryVO) throws Exception {
        try {
			if(queryVO==null)
				return selectAll();
			List list = this.queryForList("Costrecord.selectByVO", queryVO);
			return list;
        } catch (Exception e) {
			log.error("CostrecordDaoImpl的selectByVO时出错误!", e);
			throw e ;
		}
    }
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(CostrecordQuery queryVO,int pageIndex,int pageSize,Integer total) throws Exception {
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Costrecord.selectAll";
        else 
        	sqlStr = "Costrecord.selectByVO";
        try{
	        return queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
        }catch(Exception e) {
            log.error("CostrecordDaoImpl分页查询selectByVOPage时出错误!", e);
			throw e ;
        }
    }
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Costrecord record) throws Exception {
    	if(record==null)
    		return null;
        try {
			return (Long)super.insert("Costrecord.insert", record);
        }catch(Exception e) {
            log.error("CostrecordDaoImpl插入insert时出错误!", e);
			throw e ;
        }
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Costrecord record) throws Exception {
    	if(record==null||record.getCostrecordid()==null)
    		return 0;
        try {
			int rows = super.update("Costrecord.updateByPK", record);
			return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl更新updateByPK时出错误!", e);
			throw e ;
        }
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Costrecord save(Costrecord record) throws Exception {
    	if(record==null)
    		return null;
    	try {
			if(record.getCostrecordid()==null||record.getCostrecordid().intValue()==0){
				Long pkValue = this.insert(record);
				record.setCostrecordid(pkValue);
				return record;
			}else{
				this.updateByPK(record);
				return record;
			}
		} catch (RuntimeException e) {
			log.error("CostrecordDaoImpl保存save时出错误!", e);
			throw e ;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception {
    	if(pk==null)
    		return 0;
        try {
			int rows = super.delete("Costrecord.deleteByPK", pk);
			return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl删除deleteByPK时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * 根据objectID删除记录
     * @param objectID
     * @return
     * @throws Exception
     */
    public int delByObjectID(Long objectID) throws Exception{
    	if(objectID==null)
    		return 0;
        try {
			int rows = super.delete("Costrecord.delByObjectID", objectID);
			return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl删除delByObjectID时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * 根据帐户ID删除记录
     * @param userID
     * @return
     * @throws Exception
     */
    public int delByAccountID(Long userID) throws Exception{
    	if(userID==null)
    		return 0;
        try {
			int rows = super.delete("Costrecord.delByAccountID", userID);
			return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl删除delByAccountID时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(CostrecordQuery queryVO) throws Exception {
    	if(queryVO==null)
    		return 0;
        try {
			int rows = super.delete("Costrecord.deleteByVO",queryVO);
			return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl删除deleteByVO时出错误!", e);
			throw e ;
        }
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.insertBatch("Costrecord.insert", list);
        	return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl批量新增insertBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.updateBatch("Costrecord.updateByPK", list);
        	return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl批量修改updateBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.deleteBatch("Costrecord.deleteByPK", pkArray);
        	return rows;
        }catch(Exception e) {
            log.error("CostrecordDaoImpl删除deleteBatchByPK(Long[] pkArray)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
    	try {
			for(int i=0;i<pkArray.length;i++){
				if(pkArray[i]!=null)
					arrs[i] = new Long(Long.parseLong(pkArray[i]));
			}
			rows = this.deleteBatchByPK(arrs);
			return rows;
		} catch (NumberFormatException e) {
			log.error("CostrecordDaoImpl删除deleteBatchByPK(String[] pkArray)时出现转换错�?!", e);
			throw new Exception("NumberFormatException：from String to Long!") ;
		}catch(Exception e) {
            log.error("CostrecordDaoImpl删除deleteBatchByPK(String[] pkArray)时出错误!", e);
			throw e ;
        }
    	
    }
    
    /**
     * static spring getMethod
     */
     public static CostrecordDao getInstance() {
       	 CostrecordDao dao = (CostrecordDao)BeanFactory.getBeanFactory().getBean("costrecordDaoProxy");
         return dao;
     }
    
}
