package platform.daoImpl;

import java.util.List;
import org.apache.log4j.Logger;
import commonTool.base.BaseDao;
import commonTool.base.Page;
import platform.dao.ShopappDao;
import commonTool.constant.CommonConstant;
import platform.vo.Shopapp;
import platform.dto.ShopappQuery;
import platform.bean.BeanFactory;

public class ShopappDaoImpl extends BaseDao implements ShopappDao {

	static Logger log = Logger.getLogger(ShopappDaoImpl.class.getName());
	
    /**
     *
     */
    public ShopappDaoImpl() {
        super();
    }
    
    /**
     * select some record by PK
     */
    public Shopapp selectByPK(Long pk) {
    	if(pk==null)
    		return null;
		Shopapp record = (Shopapp) this.queryForObject("Shopapp.selectByPK", pk);
		return record;
    }
    
    /**
     * select all records
     * @return
     */
    public List selectAll() throws Exception {
    	try {
			List list = this.queryForList("Shopapp.selectAll", null);
			return list;
		} catch (Exception e) {
			log.error("ShopappDaoImpl的selectAll时出错误!", e);
			throw e ;
		}
    }
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ShopappQuery queryVO) throws Exception {
        try {
			if(queryVO==null)
				return selectAll();
			List list = this.queryForList("Shopapp.selectByVO", queryVO);
			return list;
        } catch (Exception e) {
			log.error("ShopappDaoImpl的selectByVO时出错误!", e);
			throw e ;
		}
    }
       
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(ShopappQuery queryVO,int pageIndex,int pageSize,Integer total) throws Exception {
        if(pageIndex<=0)
        	pageIndex = 1;
        if(pageSize<=0)
        	pageSize = CommonConstant.PAGESIZE;
        String sqlStr = "";
        if(queryVO==null)
        	sqlStr = "Shopapp.selectAll";
        else 
        	sqlStr = "Shopapp.selectByVO";
        try{
	        return queryForPage(sqlStr, queryVO, pageIndex, pageSize, total);
        }catch(Exception e) {
            log.error("ShopappDaoImpl分页查询selectByVOPage时出错误!", e);
			throw e ;
        }
    }
           
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shopapp record) throws Exception {
    	if(record==null)
    		return null;
        try {
			return (Long)super.insert("Shopapp.insert", record);
        }catch(Exception e) {
            log.error("ShopappDaoImpl插入insert时出错误!", e);
			throw e ;
        }
    }

    /**
     * update a record By PK
     */
    public int updateByPK(Shopapp record) throws Exception {
    	if(record==null||record.getShopappid()==null)
    		return 0;
        try {
			int rows = super.update("Shopapp.updateByPK", record);
			return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl更新updateByPK时出错误!", e);
			throw e ;
        }
    }

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Shopapp save(Shopapp record) throws Exception {
    	if(record==null)
    		return null;
    	try {
			if(record.getShopappid()==null||record.getShopappid().intValue()==0){
				Long pkValue = this.insert(record);
				record.setShopappid(pkValue);
				return record;
			}else{
				this.updateByPK(record);
				return record;
			}
		} catch (RuntimeException e) {
			log.error("ShopappDaoImpl保存save时出错误!", e);
			throw e ;
		}
    }

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception {
    	if(pk==null)
    		return 0;
        try {
			int rows = super.delete("Shopapp.deleteByPK", pk);
			return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl删除deleteByPK时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(ShopappQuery queryVO) throws Exception {
    	if(queryVO==null)
    		return 0;
        try {
			int rows = super.delete("Shopapp.deleteByVO",queryVO);
			return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl删除deleteByVO时出错误!", e);
			throw e ;
        }
    }
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.insertBatch("Shopapp.insert", list);
        	return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl批量新增insertBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list) throws Exception {
    	if(list==null||list.size()<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.updateBatch("Shopapp.updateByPK", list);
        	return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl批量修改updateBatch(List list)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
        try {
        	rows = super.deleteBatch("Shopapp.deleteByPK", pkArray);
        	return rows;
        }catch(Exception e) {
            log.error("ShopappDaoImpl删除deleteBatchByPK(Long[] pkArray)时出错误!", e);
			throw e ;
        }
    }
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray) throws Exception {
    	if(pkArray==null||pkArray.length<=0)
    		return 0;
    	int rows = 0;
    	Long[] arrs = new Long[pkArray.length];
    	try {
			for(int i=0;i<pkArray.length;i++){
				if(pkArray[i]!=null)
					arrs[i] = new Long(Long.parseLong(pkArray[i]));
			}
			rows = this.deleteBatchByPK(arrs);
			return rows;
		} catch (NumberFormatException e) {
			log.error("ShopappDaoImpl删除deleteBatchByPK(String[] pkArray)时出现转换错�?!", e);
			throw new Exception("NumberFormatException：from String to Long!") ;
		}catch(Exception e) {
            log.error("ShopappDaoImpl删除deleteBatchByPK(String[] pkArray)时出错误!", e);
			throw e ;
        }
    	
    }
    
    /**
     * 查询user申请了多少个商店
     * @param userid
     * @return
     */
    public int selectCountByOwner(Long userid, Short appstatus){
    	int rtnum = 0;
    	Shopapp appvo = new Shopapp();
    	appvo.setUserid(userid);
    	appvo.setAppstatus(appstatus);
    	if(userid!=null){
    	   Integer num = (Integer) this.queryForObject("Shopapp.selectCountByOwner", appvo);
    	   if(num!=null){
    		   rtnum = num;
    	   }
    	}
    	return rtnum;
    }
    
    /**
     * static spring getMethod
     */
     public static ShopappDao getInstance() {
       	 ShopappDao dao = (ShopappDao)BeanFactory.getBeanFactory().getBean("shopappDao");
         return dao;
     }
    
}
