package platform.daoImpl;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import platform.bean.BeanFactory;
import platform.dao.ShopstatuslogDao;
import platform.dto.ShopstatuslogQuery;
import platform.vo.Shopstatuslog;

import commonTool.base.BaseDao;

public class ShopstatuslogDaoImpl extends BaseDao implements ShopstatuslogDao {

	static Logger log = Logger.getLogger(ShopstatuslogDaoImpl.class.getName());
	
    /**
     *
     */
    public ShopstatuslogDaoImpl() {
        super();
    }
    
           
    /**
     * select records by queryVO
     */
    public List selectByVO(ShopstatuslogQuery queryVO)  {
		if(queryVO==null)
			return new ArrayList();
		List list = this.queryForList("Shopstatuslog.selectByVO", queryVO);
		return list;
    }
    
    /**
     * select records by shopID
     */
    public List selectByShopID(Long shopid) {
		if(shopid==null)
           return new ArrayList();
		List list = this.queryForList("Shopstatuslog.selectByShopID", shopid);
		return list;
    }
           
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shopstatuslog record)  {
    	if(record==null)
    		return null;
		return (Long)super.insert("Shopstatuslog.insert", record);
    }
    
    /**
     * delete records by shopid
     */
    public int deleteByShop(Long shopid)  {
    	if(shopid==null)
    		return 0;
		int rows = super.delete("Shopstatuslog.deleteByShop",shopid);
		return rows;
    }

     
    /**
     * static spring getMethod
     */
     public static ShopstatuslogDao getInstance()  {
    	 ShopstatuslogDao dao = (ShopstatuslogDao)BeanFactory.getBeanFactory().getBean("shopstatuslogDao");
         return dao;
     }
    
}
