package acegi.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CustorderExample extends Custorder {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int orderid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int userid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int ordercode_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int ordername_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int ordertype_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int ordertime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int baseaccountid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int reqendtime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int fullcost_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int prepaycost_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int discount_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int prepaytime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int fullpaytime_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int payway_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int paystatus_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int orderstatus_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrderid_Indicator() {
	return orderid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrderid_Indicator(int orderid_Indicator) {
	this.orderid_Indicator = orderid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getUserid_Indicator() {
	return userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setUserid_Indicator(int userid_Indicator) {
	this.userid_Indicator = userid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrdercode_Indicator() {
	return ordercode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdercode_Indicator(int ordercode_Indicator) {
	this.ordercode_Indicator = ordercode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrdername_Indicator() {
	return ordername_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdername_Indicator(int ordername_Indicator) {
	this.ordername_Indicator = ordername_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrdertype_Indicator() {
	return ordertype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdertype_Indicator(int ordertype_Indicator) {
	this.ordertype_Indicator = ordertype_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrdertime_Indicator() {
	return ordertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdertime_Indicator(int ordertime_Indicator) {
	this.ordertime_Indicator = ordertime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getBaseaccountid_Indicator() {
	return baseaccountid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setBaseaccountid_Indicator(int baseaccountid_Indicator) {
	this.baseaccountid_Indicator = baseaccountid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getReqendtime_Indicator() {
	return reqendtime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setReqendtime_Indicator(int reqendtime_Indicator) {
	this.reqendtime_Indicator = reqendtime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getFullcost_Indicator() {
	return fullcost_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setFullcost_Indicator(int fullcost_Indicator) {
	this.fullcost_Indicator = fullcost_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getPrepaycost_Indicator() {
	return prepaycost_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPrepaycost_Indicator(int prepaycost_Indicator) {
	this.prepaycost_Indicator = prepaycost_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getDiscount_Indicator() {
	return discount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setDiscount_Indicator(int discount_Indicator) {
	this.discount_Indicator = discount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getPrepaytime_Indicator() {
	return prepaytime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPrepaytime_Indicator(int prepaytime_Indicator) {
	this.prepaytime_Indicator = prepaytime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getFullpaytime_Indicator() {
	return fullpaytime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setFullpaytime_Indicator(int fullpaytime_Indicator) {
	this.fullpaytime_Indicator = fullpaytime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getPayway_Indicator() {
	return payway_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPayway_Indicator(int payway_Indicator) {
	this.payway_Indicator = payway_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getPaystatus_Indicator() {
	return paystatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPaystatus_Indicator(int paystatus_Indicator) {
	this.paystatus_Indicator = paystatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getOrderstatus_Indicator() {
	return orderstatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table custorder
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrderstatus_Indicator(int orderstatus_Indicator) {
	this.orderstatus_Indicator = orderstatus_Indicator;
    }
}