package acegi.vo;

import java.util.Date;

public class Custorder {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long orderid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.userID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long userid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderCode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String ordercode;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderName
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String ordername;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short ordertype;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Date ordertime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.baseAccountID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long baseaccountid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.reqEndTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Date reqendtime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.fullCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Double fullcost;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.prePayCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Double prepaycost;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.discount
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Double discount;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.prePayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Date prepaytime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.fullPayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Date fullpaytime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.payWay
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short payway;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.payStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short paystatus;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column custorder.orderStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short orderstatus;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderID
     * @return  the value of custorder.orderID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getOrderid() {
	return orderid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderID
     * @param orderid  the value for custorder.orderID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrderid(Long orderid) {
	this.orderid = orderid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.userID
     * @return  the value of custorder.userID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getUserid() {
	return userid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.userID
     * @param userid  the value for custorder.userID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setUserid(Long userid) {
	this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderCode
     * @return  the value of custorder.orderCode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getOrdercode() {
	return ordercode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderCode
     * @param ordercode  the value for custorder.orderCode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdercode(String ordercode) {
	this.ordercode = ordercode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderName
     * @return  the value of custorder.orderName
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getOrdername() {
	return ordername;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderName
     * @param ordername  the value for custorder.orderName
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdername(String ordername) {
	this.ordername = ordername;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderType
     * @return  the value of custorder.orderType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getOrdertype() {
	return ordertype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderType
     * @param ordertype  the value for custorder.orderType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdertype(Short ordertype) {
	this.ordertype = ordertype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderTime
     * @return  the value of custorder.orderTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Date getOrdertime() {
	return ordertime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderTime
     * @param ordertime  the value for custorder.orderTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrdertime(Date ordertime) {
	this.ordertime = ordertime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.baseAccountID
     * @return  the value of custorder.baseAccountID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getBaseaccountid() {
	return baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.baseAccountID
     * @param baseaccountid  the value for custorder.baseAccountID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setBaseaccountid(Long baseaccountid) {
	this.baseaccountid = baseaccountid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.reqEndTime
     * @return  the value of custorder.reqEndTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Date getReqendtime() {
	return reqendtime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.reqEndTime
     * @param reqendtime  the value for custorder.reqEndTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setReqendtime(Date reqendtime) {
	this.reqendtime = reqendtime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.fullCost
     * @return  the value of custorder.fullCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Double getFullcost() {
	return fullcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.fullCost
     * @param fullcost  the value for custorder.fullCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setFullcost(Double fullcost) {
	this.fullcost = fullcost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.prePayCost
     * @return  the value of custorder.prePayCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Double getPrepaycost() {
	return prepaycost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.prePayCost
     * @param prepaycost  the value for custorder.prePayCost
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPrepaycost(Double prepaycost) {
	this.prepaycost = prepaycost;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.discount
     * @return  the value of custorder.discount
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Double getDiscount() {
	return discount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.discount
     * @param discount  the value for custorder.discount
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setDiscount(Double discount) {
	this.discount = discount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.prePayTime
     * @return  the value of custorder.prePayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Date getPrepaytime() {
	return prepaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.prePayTime
     * @param prepaytime  the value for custorder.prePayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPrepaytime(Date prepaytime) {
	this.prepaytime = prepaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.fullPayTime
     * @return  the value of custorder.fullPayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Date getFullpaytime() {
	return fullpaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.fullPayTime
     * @param fullpaytime  the value for custorder.fullPayTime
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setFullpaytime(Date fullpaytime) {
	this.fullpaytime = fullpaytime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.payWay
     * @return  the value of custorder.payWay
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getPayway() {
	return payway;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.payWay
     * @param payway  the value for custorder.payWay
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPayway(Short payway) {
	this.payway = payway;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.payStatus
     * @return  the value of custorder.payStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getPaystatus() {
	return paystatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.payStatus
     * @param paystatus  the value for custorder.payStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPaystatus(Short paystatus) {
	this.paystatus = paystatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column custorder.orderStatus
     * @return  the value of custorder.orderStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getOrderstatus() {
	return orderstatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column custorder.orderStatus
     * @param orderstatus  the value for custorder.orderStatus
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOrderstatus(Short orderstatus) {
	this.orderstatus = orderstatus;
    }
}