package acegi.vo;

public class Menus {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long id;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.title
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String title;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.target
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String target;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.onclick
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String onclick;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.onmouseover
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String onmouseover;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.onmouseout
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String onmouseout;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.image
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String image;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.altImage
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String altimage;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.tooltip
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String tooltip;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.page
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String page;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.width
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String width;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.height
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String height;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.forward
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String forward;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.action
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String action;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column menus.menuType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short menutype;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.id
     * @return  the value of menus.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getId() {
	return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.id
     * @param id  the value for menus.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setId(Long id) {
	this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.title
     * @return  the value of menus.title
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getTitle() {
	return title;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.title
     * @param title  the value for menus.title
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setTitle(String title) {
	this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.target
     * @return  the value of menus.target
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getTarget() {
	return target;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.target
     * @param target  the value for menus.target
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setTarget(String target) {
	this.target = target;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.onclick
     * @return  the value of menus.onclick
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getOnclick() {
	return onclick;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.onclick
     * @param onclick  the value for menus.onclick
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOnclick(String onclick) {
	this.onclick = onclick;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.onmouseover
     * @return  the value of menus.onmouseover
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getOnmouseover() {
	return onmouseover;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.onmouseover
     * @param onmouseover  the value for menus.onmouseover
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOnmouseover(String onmouseover) {
	this.onmouseover = onmouseover;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.onmouseout
     * @return  the value of menus.onmouseout
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getOnmouseout() {
	return onmouseout;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.onmouseout
     * @param onmouseout  the value for menus.onmouseout
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setOnmouseout(String onmouseout) {
	this.onmouseout = onmouseout;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.image
     * @return  the value of menus.image
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getImage() {
	return image;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.image
     * @param image  the value for menus.image
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setImage(String image) {
	this.image = image;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.altImage
     * @return  the value of menus.altImage
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getAltimage() {
	return altimage;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.altImage
     * @param altimage  the value for menus.altImage
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setAltimage(String altimage) {
	this.altimage = altimage;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.tooltip
     * @return  the value of menus.tooltip
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getTooltip() {
	return tooltip;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.tooltip
     * @param tooltip  the value for menus.tooltip
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setTooltip(String tooltip) {
	this.tooltip = tooltip;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.page
     * @return  the value of menus.page
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getPage() {
	return page;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.page
     * @param page  the value for menus.page
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setPage(String page) {
	this.page = page;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.width
     * @return  the value of menus.width
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getWidth() {
	return width;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.width
     * @param width  the value for menus.width
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setWidth(String width) {
	this.width = width;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.height
     * @return  the value of menus.height
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getHeight() {
	return height;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.height
     * @param height  the value for menus.height
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setHeight(String height) {
	this.height = height;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.forward
     * @return  the value of menus.forward
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getForward() {
	return forward;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.forward
     * @param forward  the value for menus.forward
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setForward(String forward) {
	this.forward = forward;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.action
     * @return  the value of menus.action
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getAction() {
	return action;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.action
     * @param action  the value for menus.action
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setAction(String action) {
	this.action = action;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column menus.menuType
     * @return  the value of menus.menuType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getMenutype() {
	return menutype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column menus.menuType
     * @param menutype  the value for menus.menuType
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setMenutype(Short menutype) {
	this.menutype = menutype;
    }
}