package acegi.vo;

public class ResclinkKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resclink.linkID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long linkid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resclink.methodID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long methodid;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resclink.linkID
     * @return  the value of resclink.linkID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getLinkid() {
	return linkid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resclink.linkID
     * @param linkid  the value for resclink.linkID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setLinkid(Long linkid) {
	this.linkid = linkid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resclink.methodID
     * @return  the value of resclink.methodID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getMethodid() {
	return methodid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resclink.methodID
     * @param methodid  the value for resclink.methodID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setMethodid(Long methodid) {
	this.methodid = methodid;
    }
}