package acegi.vo;

public class ResclinkExample extends Resclink {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int linkid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int methodid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int back1_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getLinkid_Indicator() {
	return linkid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setLinkid_Indicator(int linkid_Indicator) {
	this.linkid_Indicator = linkid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getMethodid_Indicator() {
	return methodid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setMethodid_Indicator(int methodid_Indicator) {
	this.methodid_Indicator = methodid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getBack1_Indicator() {
	return back1_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table resclink
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setBack1_Indicator(int back1_Indicator) {
	this.back1_Indicator = back1_Indicator;
    }
}