package acegi.vo;

public class Resources {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.id
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private Long id;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.name
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private String name;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.res_type
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private String resType;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.res_string
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private String resString;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.syscode
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private String syscode;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.upId
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private Long upid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.ordNo
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private Integer ordno;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.status
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private Short status;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column resources.descn
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    private String descn;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.id
     * @return  the value of resources.id
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public Long getId() {
	return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.id
     * @param id  the value for resources.id
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setId(Long id) {
	this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.name
     * @return  the value of resources.name
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public String getName() {
	return name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.name
     * @param name  the value for resources.name
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setName(String name) {
	this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.res_type
     * @return  the value of resources.res_type
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public String getResType() {
	return resType;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.res_type
     * @param resType  the value for resources.res_type
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setResType(String resType) {
	this.resType = resType;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.res_string
     * @return  the value of resources.res_string
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public String getResString() {
	return resString;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.res_string
     * @param resString  the value for resources.res_string
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setResString(String resString) {
	this.resString = resString;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.syscode
     * @return  the value of resources.syscode
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public String getSyscode() {
	return syscode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.syscode
     * @param syscode  the value for resources.syscode
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setSyscode(String syscode) {
	this.syscode = syscode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.upId
     * @return  the value of resources.upId
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public Long getUpid() {
	return upid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.upId
     * @param upid  the value for resources.upId
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setUpid(Long upid) {
	this.upid = upid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.ordNo
     * @return  the value of resources.ordNo
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public Integer getOrdno() {
	return ordno;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.ordNo
     * @param ordno  the value for resources.ordNo
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setOrdno(Integer ordno) {
	this.ordno = ordno;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.status
     * @return  the value of resources.status
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public Short getStatus() {
	return status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.status
     * @param status  the value for resources.status
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setStatus(Short status) {
	this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column resources.descn
     * @return  the value of resources.descn
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public String getDescn() {
	return descn;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column resources.descn
     * @param descn  the value for resources.descn
     * @abatorgenerated  Wed Sep 24 23:16:27 CST 2008
     */
    public void setDescn(String descn) {
	this.descn = descn;
    }
}