package acegi.vo;

public class RolesvalueExample extends Rolesvalue {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_IGNORE = 0;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NULL = 1;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_NULL = 2;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_EQUALS = 3;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN = 5;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN = 7;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public static final int EXAMPLE_LIKE = 9;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private boolean combineTypeOr;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int valueid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int id_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int localeid_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int name_Indicator;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private int shopid_Indicator;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
	this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public boolean isCombineTypeOr() {
	return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getValueid_Indicator() {
	return valueid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setValueid_Indicator(int valueid_Indicator) {
	this.valueid_Indicator = valueid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getId_Indicator() {
	return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setId_Indicator(int id_Indicator) {
	this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getLocaleid_Indicator() {
	return localeid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setLocaleid_Indicator(int localeid_Indicator) {
	this.localeid_Indicator = localeid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getName_Indicator() {
	return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setName_Indicator(int name_Indicator) {
	this.name_Indicator = name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public int getShopid_Indicator() {
	return shopid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table rolesvalue
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setShopid_Indicator(int shopid_Indicator) {
	this.shopid_Indicator = shopid_Indicator;
    }
}