package acegi.vo;

public class Roles {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long id;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.name
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String name;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.shopID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long shopid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.syscode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String syscode;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.upId
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long upid;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.status
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short status;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.isDefaultSet
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short isdefaultset;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column roles.descn
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private String descn;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.id
     * @return  the value of roles.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getId() {
	return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.id
     * @param id  the value for roles.id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setId(Long id) {
	this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.name
     * @return  the value of roles.name
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getName() {
	return name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.name
     * @param name  the value for roles.name
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setName(String name) {
	this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.shopID
     * @return  the value of roles.shopID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getShopid() {
	return shopid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.shopID
     * @param shopid  the value for roles.shopID
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setShopid(Long shopid) {
	this.shopid = shopid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.syscode
     * @return  the value of roles.syscode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getSyscode() {
	return syscode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.syscode
     * @param syscode  the value for roles.syscode
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setSyscode(String syscode) {
	this.syscode = syscode;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.upId
     * @return  the value of roles.upId
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getUpid() {
	return upid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.upId
     * @param upid  the value for roles.upId
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setUpid(Long upid) {
	this.upid = upid;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.status
     * @return  the value of roles.status
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getStatus() {
	return status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.status
     * @param status  the value for roles.status
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setStatus(Short status) {
	this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.isDefaultSet
     * @return  the value of roles.isDefaultSet
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getIsdefaultset() {
	return isdefaultset;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.isDefaultSet
     * @param isdefaultset  the value for roles.isDefaultSet
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setIsdefaultset(Short isdefaultset) {
	this.isdefaultset = isdefaultset;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column roles.descn
     * @return  the value of roles.descn
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public String getDescn() {
	return descn;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column roles.descn
     * @param descn  the value for roles.descn
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setDescn(String descn) {
	this.descn = descn;
    }
}