package acegi.vo;

public class UserRole extends UserRoleKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user_role.usetype
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Short usetype;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user_role.usetype
     * @return  the value of user_role.usetype
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Short getUsetype() {
	return usetype;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user_role.usetype
     * @param usetype  the value for user_role.usetype
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setUsetype(Short usetype) {
	this.usetype = usetype;
    }
}