package acegi.vo;

public class UserRoleKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user_role.role_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long roleId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column user_role.user_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    private Long userId;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user_role.role_id
     * @return  the value of user_role.role_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getRoleId() {
	return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user_role.role_id
     * @param roleId  the value for user_role.role_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setRoleId(Long roleId) {
	this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column user_role.user_id
     * @return  the value of user_role.user_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public Long getUserId() {
	return userId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column user_role.user_id
     * @param userId  the value for user_role.user_id
     * @abatorgenerated  Wed Sep 24 23:16:28 CST 2008
     */
    public void setUserId(Long userId) {
	this.userId = userId;
    }
}