package netTest.product.dao;

import netTest.product.vo.Coursepost;

import commonTool.base.Page;

public interface CoursepostDao {
   
    /**
     * select some record by PK
     */
    public Coursepost selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
//    public List selectByVO(ShoppostQuery queryVO);
    
    /**
     * select page by queryVO 
     */
    public Page selectByVOPage(Long productid, String caption, 
    						   int pageIndex, int pageSize, Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Coursepost record);

    /**
     * update a record By PK
     */
    public int updateByPK(Coursepost record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Coursepost save(Coursepost record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
	
}
