package netTest.product.dao;

import java.util.Date;
import java.util.List;

import netTest.product.dto.UserprodbuylogQuery;
import netTest.product.vo.Userprodbuylog;
import netTest.product.vo.Userproduct;

import commonTool.base.Page;

public interface UserprodbuylogDao {
   
        
    /**
     * select records by queryVO
     */
    public List selectByVO(UserprodbuylogQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(UserprodbuylogQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Userprodbuylog record);


    /**
     * 根据订单条目vo和用户产品id记录用户购买产品记录
     * @param itemVO
     * @param userproductid
     * @return
     */
    public boolean logUserProduct(List<Userproduct> usrprdList, Long orderid, Date happendate, Short action);
	
}
