package platform.dao;

import java.util.List;
import commonTool.base.Page;
import platform.vo.Custinfoex;
import platform.dto.CustinfoexQuery;

public interface CustinfoexDao {
   
    /**
     * select some record by PK
     */
    public Custinfoex selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(CustinfoexQuery queryVO)  ;
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @
     */
    public Page selectByVOPage(CustinfoexQuery queryVO,int pageIndex,int pageSize,Integer total)  ;
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Custinfoex record)  ;

    /**
     * update a record By PK
     */
    public int updateByPK(Custinfoex record)  ;

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @
     */
    public Custinfoex save(Custinfoex record)  ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(CustinfoexQuery queryVO)  ;

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list)  ;
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list)  ;
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray)  ;
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray)  ;
	
}
