package platform.dao;

import java.util.List;

import platform.dto.CuststatusQuery;
import platform.vo.Custstatus;

public interface CuststatusDao {
   
    /**
     * select records by userid
     */
    public List selectByUserid(Long userid);
    
    public Custstatus selectUserLastChange(Long userid);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(CuststatusQuery queryVO) ;
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Custstatus record) ;

    /**
     * delete a record by userID
     */
    public int deleteByUserID(Long userID);
    	
}
