package platform.dao;

import java.util.List;

import platform.vo.Hotcategory;

public interface HotcategoryDao {
   
    /**
     * 是否存在该热门目录
     * @param categoryid
     * @param pid
     * @param localeid
     * @return -1代表缺少参数，1为存在，0为不存在
     */
    public int exists(Long categoryid, Long localeid, String syscode);
    
    /**
     * 该热门目录是否存在子目录
     * @param categoryid
     * @return -1代表缺少参数，1为存在，0为不存在
     */
    public int existsChild(Long categoryid, String syscode);
	
    /**
     * 根据localeid选择所有本国的热门目录，包括一级和二级目录
     */
    public List<Hotcategory> selectBySyscodeLocale(Long localeid, String syscode, Short categorystatus);
                
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Hotcategory record);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * 删除指定目录的所有国家语言设置
     * @param categoryid
     * @param pid
     * @return
     */
    public int delCategoryAllLocale(Long categoryid, String syscode);
    
    public int deleteByPK(Long categoryid, Long localeid, String syscode);
    
    /**
     * 插入该热门目录的所有的locale记录
     */
    public Long insertAllLocale(Hotcategory record);
	
}
