package platform.dao;

import java.util.Date;
import java.util.List;

import platform.vo.Infonews;

import commonTool.base.Page;

public interface InfonewsDao {
   
    /**
     * select some record by PK
     */
    public Infonews selectByPK(Long pk);
            
    /**
     * select records by queryVO
     */
//    public List selectByRefID(Long refid, Short status);
        
    /**
     * 搜索新闻
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     */
    public Page selectResult(Long refid, Long categoryid, Long localeid, String content, int pageIndex, int pageSize,Integer total);
        
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Infonews record);

    /**
     * update a record By PK
     */
    public int updateByPK(Infonews record);

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Infonews save(Infonews record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray);
    
    /**
     * 查询超过给定时间的数据，主要是为清理脏数据使用
     * 仅仅返回前600条数据，需要反复调用处理
     */
    public List<Long> selectLongTimeData(Date date, Short status);
	
}
