package platform.dao;

import java.util.List;

import platform.vo.Newscategory;

public interface NewscategoryDao {
   
	public Newscategory selectByPK(Long pk);
	
    /**
     * select some record by PK
     */
    public Newscategory selectByLogicPK(Long pk, Long localeid);
    
    /**
     * 查询需要显示的标签
     * @param categoryid
     * @param module
     * @param localeid
     * @return
     */
    public List<Newscategory> selectCateTab(Long categoryid, Long localeid);
    
    /**
     * 查询某个标签对应的不同语言国家的值
     * @param newscategoryid
     * @return
     */
    public List<Newscategory> selectTabLocale(Long newscategoryid);
               
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Newscategory insert(Newscategory record);

    /**
     * update a record By PK
     */
    public void updateByPK(Newscategory record);
    
    public Long saveNewsCateValue(Newscategory vo);
    
    /**
     * 删除一个tab页，包括其下各国语言的tab
     * @param pk: 要删除的tab的pk值
     */
    public void delOneTab(Long newscategoryid);
    
    /**
     * 删除一个目录的value记录，即一种语言的目录记录
     * @param valueid
     */
    public void delOneTabLocale(Long valueid);
    
}
