package platform.dao;

import java.util.List;

import platform.dto.ProductcategoryvalueQuery;
import platform.vo.Productcategoryvalue;

import commonTool.base.Page;

public interface ProductcategoryvalueDao {
   
    /**
     * select some record by PK
     */
    public Productcategoryvalue selectByPK(Long pk);
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ProductcategoryvalueQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @
     */
    public Page selectByVOPage(ProductcategoryvalueQuery queryVO,int pageIndex,int pageSize,Integer total)  ;
    
    /**
     * 根据目录id查询该目录已经设置的国家语言集合字符串，其中用","隔开各个localeid
     * @param categoryid
     * @return
     * @
     */
    public String qrySelectedLocaleStr(Long categoryid) ;
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Productcategoryvalue record)  ;

    /**
     * update a record By PK
     */
    public int updateByPK(Productcategoryvalue record)  ;

	/**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @
     */
    public Productcategoryvalue save(Productcategoryvalue record)  ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk)  ;
    
    /**
     * delete a record by categoryid，同时删除该categoryid对应的所有下级记录
     * 在sql语句中实现
     */
    public int deleteByCategoryidChild(Long categoryid) ;
    
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray)  ;
	
}
