package platform.dao;

import java.util.List;
import commonTool.base.Page;
import platform.vo.Shopcosrecdet;
import platform.dto.ShopcosrecdetQuery;

public interface ShopcosrecdetDao {
   
    /**
     * select some record by PK
     */
    public Shopcosrecdet selectByPK(Long pk);
    
    /**
     * select all records
     * @return
     */
    public List selectAll() throws Exception ;
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ShopcosrecdetQuery queryVO) throws Exception ;
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(ShopcosrecdetQuery queryVO,int pageIndex,int pageSize,Integer total) throws Exception ;
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shopcosrecdet record) throws Exception ;

    /**
     * update a record By PK
     */
    public int updateByPK(Shopcosrecdet record) throws Exception ;

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Shopcosrecdet save(Shopcosrecdet record) throws Exception ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) throws Exception ;
    
    /**
     * delete records by queryVO
     */
    public int deleteByVO(ShopcosrecdetQuery queryVO) throws Exception ;

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) throws Exception ;
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list) throws Exception ;
    
    /**
     * deleteBatch records by the Long Array of PK
     */
    public int deleteBatchByPK(Long[] pkArray) throws Exception ;
    
    /**
     * deleteBatch records by the String Array of PK
     */
    public int deleteBatchByPK(String[] pkArray) throws Exception ;
    
    /**
     * 根据帐户ID删除记录
     * @param baseaccountid
     * @return
     * @throws Exception
     */
    public int delByAccountID(Long baseaccountid) throws Exception;
    
    /**
     * 根据shopID删除记录
     * @param shopID
     * @return
     * @throws Exception
     */
    public int delByShopID(Long shopID) throws Exception;
	
}
