package platform.dao;

import java.util.List;

import platform.dto.ShopstatuslogQuery;
import platform.vo.Shopstatuslog;

public interface ShopstatuslogDao {
       
    public List selectByShopID(Long shopid);
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ShopstatuslogQuery queryVO);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shopstatuslog record);

    /**
     * delete a record by PK
     */
    public int deleteByShop(Long shopid);
    
	
}
