package platform.dao;

import java.util.List;
import commonTool.base.Page;
import platform.vo.Shopfunc;
import platform.dto.ShopfuncQuery;

public interface ShopfuncDao {
   
    /**
     * select some record by PK
     */
    public Shopfunc selectByPK(Long pk);
    
    public Shopfunc selectByLogicPK(Long shopid, String functionCode);
        
    /**
     * select records by queryVO
     */
    public List selectByVO(ShopfuncQuery queryVO) ;
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Shopfunc record) ;

    /**
     * update a record By PK
     */
    public int updateByPK(Shopfunc record) ;

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @throws Exception
     */
    public Shopfunc save(Shopfunc record) ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) ;
    
    /**
     * delete records by logic pk
     */
    public int deleteByLogicPK(Long shopid, String functionCode) ;

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list) ;
    
    /**
     * updateBatch records of List
     */
    public int updateBatch(List list) ;
    	
}
