package platform.dao;

import java.util.List;
import commonTool.base.Page;
import platform.vo.Sysproductcate;
import platform.dto.SysproductcateQuery;

public interface SysproductcateDao {
   
    /**
     * select some record by PK
     */
    public Sysproductcate selectByPK(Long categoryid,String syscode);
    
    /**
     * select all records
     * @return
     */
    public List selectAll();
        
    /**
     * select records by queryVO
     */
    public List selectByVO(SysproductcateQuery queryVO);
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(SysproductcateQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Sysproductcate record);
    
    /**
     * 根据目录id和系统编码串添加系统目录
     * @param categoryid
     * @param syscodesStr
     * @return
     */
    public int insert(Long categoryid,String syscodesStr);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long categoryid,String syscode) throws Exception ;
       
    /**
     * delete a record by category
     */
    public int deleteByCate(Long categoryid);
    
    /**
     * delete a record by PK
     */
    public int deleteBatchByPK(Long categoryid,String[] syscodeArr);
    
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
}
