package platform.dao;

import java.util.List;

import platform.dto.UserQuery;
import platform.vo.User;
import commonTool.base.Page;

public interface UserDao {
   
    /**
     * select some record by PK
     */
    public User selectByPK(Long pk);
    
    /**
     * select some record by selectByLogin
     */
    public User selectByLogin(String loginName);
    
    /**
     * select some record by email
     */
    public User selectByEmail(String email);
                
    /**
     * select records by queryVO
     */
    public List selectByVO(UserQuery queryVO) ;
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(UserQuery queryVO,int pageIndex,int pageSize,Integer total) ;
    
    public int updatePassword(String newpassword, Long userid);
    
    /**
     * 更新用户loginame, 并且更新stagestatus;更新password和status
     * @param newloginame
     * @param userid
     * @return
     */
    public int updateLoginAccountInfo(String newloginame, String password, String email, Short status, Long userid);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(User record) ;

    /**
     * update a record By PK
     */
    public int updateByPK(User record) ;
    
    public User save(User record);

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk) ;
    
    /**
     * insertBatch records of List
     */
    public int insertBatch(List list);
        
    /**
     * 根据角色id选择该角色下的用户列表
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByRoleIdPage(UserQuery queryVO,int pageIndex,int pageSize,Integer total);
    
    /**
     * 选择某角色下可选用户列表，即还没有选择的用户的列表
     * @param queryVO
     * @param pageIndex
     * @param pageSize
     * @return
     */
    public Page selectUsersForRoleAddPage(UserQuery queryVO,int pageIndex,int pageSize,Integer total);
	
}
