package platform.dao;

import java.util.List;
import commonTool.base.Page;
import platform.dto.UsershopQuery;
import platform.vo.Usershop;

public interface UsershopDao {
   
    /**
     * select some record by PK
     */
    public Usershop selectByPK(Long pk) ;
        
    /**
     * 根据shopid和userid查询出对应的用户商店对象
     * @param shopid
     * @param userid
     * @return
     * @throws Exception
     */
    public Usershop selectByLogicPK(Long shopid,Long userid) ;
           
    /**
     * select records by queryVO
     */
    public List selectByVO(UsershopQuery queryVO) ;
    
    /**
     * 查询用户加入的商店的信息
     */
    public List<Usershop> qryUserShop(Long userid, Short usershopstatus) ;
    
    /**
     * select page by queryVO 
     * @param queryVO:the query vo,if queryVO is null,then search all
     * @param pageIndex:the current page num,start from 1;
     * @param pageSize:the page size,if less equal than 0,the default PlatfromConstant.PAGESIZE will be used;
     * @return Page
     * @throws Exception
     */
    public Page selectByVOPage(UsershopQuery queryVO,int pageIndex,int pageSize,Integer total) ;
    
    /**
     * 根据用户的id查询用户
     */
    public List<Usershop> selectByUserId(Long shopid, List<Long> userList);
    
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Usershop record);

    /**
     * update a record By PK
     */
    public int updateByPK(Usershop record);
    
    /**
     * 更新用户在shop中的loginame
     */
    public int updateUserLoginame(Long userid, String newloginame);
    
    /**
     * update a record By Logic PK
     */
    public int updateByLogicPK(Usershop record);
    
    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk);
    
    /**
     * 根据shopID删除商店人员记录
     * @param shopid
     * @return
     * @throws Exception
     */
    public int deleteByShop(Long shopid);

    /**
     * delete records by userid, shopid, usershoptype
     * usershoptype: 见UsershopConstant
     */
    public int deleteUserInShop(Long userid, Long shopid, Short usershoptype);
    
    /**
     * 检查商店中是否存在该nickname
     * @param nickname
     * @param shopid
     * @return true: 存在， false: 不存在
     */
    public boolean existsNicknameInShop(String nickname, Long shopid, String syscode);
	
}
