package platform.dao;

import java.util.List;
import platform.vo.Usercontactinfo;
import platform.dto.UsercontactinfoQuery;

public interface UsercontactinfoDao {
   
    /**
     * select some record by PK
     */
    public Usercontactinfo selectByPK(Long pk)  ;   
       
    /**
     * select records by queryVO
     */
    public List selectByVO(UsercontactinfoQuery queryVO)  ;

    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Usercontactinfo record);

    /**
     * update a record By PK
     */
    public int updateByPK(Usercontactinfo record)  ;

    /**
     * update the record if exists pk,else insert the record
     * @param record
     * @return
     * @
     */
    public void save(Usercontactinfo record)  ;

    /**
     * delete a record by PK
     */
    public int deleteByPK(Long pk)  ;

	/**
     * insertBatch records of List
     */
    public int insertBatch(List list)  ;
	
}
