package platform.user.dao;

import java.util.List;

import platform.user.vo.Accountvalidatetask;

public interface AccountvalidatetaskDao {
   
    /**
     * 用于在用户点击active link的时候取出校验
     */
    public Accountvalidatetask selectUserTask(String email, String validatetype,
    		                                  String validatecode, Short status);
    
    /**
     * 查询用户最后一次的申请task的记录，用于判断用户是否重复输入多次的申请，例如重复输入多次忘记密码
     */
    public Accountvalidatetask selectLastUserTask(String email, String validatetype,
    		                                      Short status);
            
    /**
     * select records by queryVO
     */
    public List selectByVO(Accountvalidatetask vo);
       
    /**
     * insert a record
     * @return Object with the PK(generated by DB)
     */
    public Long insert(Accountvalidatetask record);

    /**
     * update a record By PK
     */
    public int updateByPK(Accountvalidatetask record);
   
	/**
     * insertBatch records of List
     */
    public int insertBatch(List list);
    
    /**
     * 删除
     */
    public void deleteUserTask(String email, String validatetype,
    		                   String validatecode);
    
    public void deleteByUserID(Long userid);
	
}
